FROM php:7.4-apache

# Instalar extensiones necesarias para Moodle
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libzip-dev \
    unzip \
    && docker-php-ext-install \
    gd \
    mysqli \
    intl \
    soap \
    curl \
    zip

# Copiar el código de Moodle a la carpeta de Apache
COPY ./html /var/www/html

# Establecer permisos para la carpeta de Moodle
RUN chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html

EXPOSE 80
