version: '3.7'

services:
  moodle_db:
    image: mysql:5.7
    container_name: moodle_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle_user
      MYSQL_PASSWORD: moodle_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - moodle_net

  moodle_web:
    build: ./apache-php
    container_name: moodle_web
    volumes:
      - ./html:/var/www/html
    ports:
      - "8081:80"
    networks:
      - moodle_net

  moodle_app:
    image: bitnami/moodle:latest
    container_name: moodle_app
    depends_on:
      - moodle_db
    ports:
      - "8082:80"
    environment:
      MOODLE_DATABASE_HOST: moodle_db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: moodle_user
      MOODLE_DATABASE_PASSWORD: moodle_password
      MOODLE_DATABASE_NAME: moodle
    volumes:
      - moodle_data:/bitnami/moodle
    networks:
      - moodle_net

volumes:
  db_data:
  moodle_data:

networks:
  moodle_net:
